name       : filemanager-actions
version    : 3.4
release    : 13
source     :
    - https://download.gnome.org/sources/filemanager-actions/3.4/filemanager-actions-3.4.tar.xz : 10189781af90df4c99fde0fe98eacd2e12f4577eff5dc9b769618d980668a997
license    :
    - GPL-2.0-or-later
    - GFDL-1.3-or-later
component  : desktop.gnome
summary    : A file-manager extension which offers user configurable context menu
    actions
description: |
    Filemanager-actions is an extension for Nautilus and Caja file managers which
    allows the user to add arbitrary program to be launched through the file
    manager popup menu of selected files. Used to be called nautilus-actions.
patterns   :
    - caja : /usr/lib64/caja
    - nautilus : /usr/lib64/nautilus
replaces   :
    - nautilus : nautilus-actions
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcaja-extension)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libnautilus-extension)
    - pkgconfig(xml2po)
setup      : |
    # fix wrong icon name at desktop launcher
    %patch -p0 < $pkgfiles/fix-icon.patch
    %configure --disable-schemas-install \
               --disable-scrollkeeper
build      : |
    %make
install    : |
    %make_install
