name       : nautilus-actions
version    : 3.2.4
release    : 2
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/nautilus-actions/3.2/nautilus-actions-3.2.4.tar.xz : 10206c952ed3e916241168ebffd7ade9b9bcc18429ab33dfe24d9517a7371567
license    :
    - GPL-2.0
    - GDFL-1.3
summary    : Nautilus-Actions
component  : desktop.gnome
description: |
    Nautilus-actions is an extension for Nautilus file manager which allows the user to add arbitrary program to be launched through the Nautilus file manager popup menu of selected files.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(ice)
    - pkgconfig(sm)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(unique-3.0)
    - pkgconfig(libnautilus-extension)
setup      : |
    %configure --disable-schemas-install
build      : |
    %make
install    : |
    %make_install
